---
- hosts: nodes
  vars:
    user1: "Priya"
    user2: "Vignesh"
    user3: "kanna"  
  tasks:
  - name: Create a user
    user:
      name: "{{ item }}"
      state: present
    with_items:
      - user1
      - user2
      - user3

