---
- hosts: nodes
  vars:
    user1: "Mona"
    user2: "Vini"
    user3: "keerthi"  
  tasks:
  - name: Create a user
    user:
      name: "{{ item }}"
      state: present
    with_items:
      - user1
      - user2
      - user3
    notify:
      - add user
   
  handlers:
    - name: add user
      user:
        name: "jan"
        state: present
  

