---
- hosts: nodes
  tasks:
  - name: install apache2
    package:
      name: apache2
      state: present
  - name: start apache2
    service:
      name: apache2
      state: started
  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
